import { StyleSheet } from 'react-native';
import { moderateScale, responsiveFont, verticalScale } from '../utils/responsive';

const styles = StyleSheet.create({
  container: { flex: 1 },
  contentArea: { flex: 1 },
  screenContainer: { flex: 1 },
  pager: { flex: 1 },
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    paddingHorizontal: moderateScale(30),
  },
  hiddenShotContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 0,
    height: 0,
    opacity: 0,
    overflow: 'hidden',
    zIndex: -1,
  },
  shareCardCapture: {
    width: 900,
    height: 900,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 90,
    position: 'absolute',
    top: 0,
    left: 0,
  },
  shareBrandRow: {
    position: 'absolute',
    top: 64,
    left: 64,
    flexDirection: 'row',
    alignItems: 'center',
  },
  shareAvatar: {
    width: 100,
    height: 100,
    borderRadius: 36,
    marginRight: 18,
  },
  shareLogo: {
    fontSize: 52,
    fontStyle: 'italic',
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  shareText: {
    fontSize: 64,
    lineHeight: 86,
    textAlign: 'center',
  },
  mainAffirmationText: {
    marginBottom: verticalScale(8),
  },
  pageActionsRow: {
    position: 'absolute',
    bottom: verticalScale(120),
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  shareButton: {
    marginTop: verticalScale(16),
  },
  text: {
    fontSize: responsiveFont(24),
    fontWeight: '600',
    lineHeight: responsiveFont(34),
    textAlign: 'center',
    paddingHorizontal: moderateScale(8),
  },
  favoriteButton: {
    marginTop: verticalScale(16),
    borderRadius: moderateScale(14),
    paddingVertical: verticalScale(12),
    paddingHorizontal: moderateScale(14),
    alignItems: 'center',
    justifyContent: 'center',
  },
  favoriteButtonText: {
    fontSize: 15,
    fontWeight: '700',
  },
  iconLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 6,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: moderateScale(24),
  },
  emptyStateTitle: {
    fontSize: responsiveFont(22),
    fontWeight: '700',
    marginBottom: verticalScale(8),
    textAlign: 'center',
  },
  emptyStateSubtitle: {
    fontSize: responsiveFont(15),
    textAlign: 'center',
  },
  fab: {
    width: moderateScale(56),
    height: moderateScale(56),
    borderRadius: moderateScale(28),
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: '#ffb48f',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
  },
  fabRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  fabOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
    paddingLeft: 20,
    paddingBottom: 30,
    zIndex: 20,
    elevation: 20,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalBox: {
    padding: 20,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    maxHeight: '70%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
    textAlign: 'center',
  },
  catRow: {
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  catItem: {
    flex: 1,
    minHeight: 72,
    marginHorizontal: 6,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 14,
  },
  catText: { fontSize: 16, textAlign: 'center' },
  catTextSelected: { fontWeight: '700' },
  check: { fontSize: 14, position: 'absolute', top: 8, right: 10, fontWeight: '700' },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 12,
  },
  actionButton: { paddingVertical: 8, paddingHorizontal: 12, marginLeft: 8 },
  applyButton: { borderRadius: 6 },
  actionText: { fontWeight: '600' },
  applyText: { color: '#ffffff' },

  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  headerButton: {
    minWidth: 40,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
  },

  favoritesList: {
    padding: moderateScale(16),
    gap: 12,
    flexGrow: 1,
  },
  favoriteCard: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
  },
  favoriteText: {
    fontSize: 17,
    lineHeight: 25,
    marginBottom: 12,
  },
  removeFavoriteButton: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  removeFavoriteButtonText: {
    fontSize: 13,
    fontWeight: '700',
  },

  settingsList: {
    padding: moderateScale(16),
    paddingBottom: verticalScale(28),
  },
  settingsSectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 4,
    marginTop: 4,
  },
  settingsSectionSubtitle: {
    fontSize: 14,
    marginBottom: 14,
  },
  themeOption: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  themeOptionTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  themeOptionSubtitle: {
    fontSize: 13,
    marginTop: 2,
  },
  settingRow: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingTextGroup: {
    flex: 1,
    paddingRight: 12,
  },
  settingTitle: {
    fontSize: 15,
    fontWeight: '700',
  },
  settingHint: {
    fontSize: 13,
    marginTop: 2,
  },
  aboutCard: {
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
    marginTop: 10,
  },
  aboutText: {
    fontSize: 14,
    lineHeight: 20,
  },

  categoriesList: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 96,
  },
  categoriesHeader: {
    marginBottom: 10,
  },
  categoryActionsBar: {
    backgroundColor: 'transparent',
    paddingHorizontal: 12,
    paddingTop: 10,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  categoryActionButton: {
    minWidth: 110,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
});

export default styles;
