export const THEMES = {
  peach: {
    key: 'peach',
    label: 'Peach Bliss',
    isDark: false,
    colors: {
      background: '#fff4ec',
      surface: '#ffe8da',
      card: '#fff6ef',
      border: '#f1b08f',
      textPrimary: '#5f3a2f',
      textSecondary: '#6f4a3b',
      accent: '#f49a6c',
      accentMuted: '#ffd8c1',
      overlay: 'rgba(108,66,50,0.35)',
      header: '#fff4ec',
      functionBtn:"#fcd9c7"
    },
  },
  apricot: {
    key: 'apricot',
    label: 'Apricot Glow',
    isDark: false,
    colors: {
      background: '#fff8f1',
      surface: '#ffead5',
      card: '#fff4e8',
      border: '#efbf95',
      textPrimary: '#5a3b24',
      textSecondary: '#765136',
      accent: '#ea8d55',
      accentMuted: '#ffd9bb',
      overlay: 'rgba(118,81,54,0.3)',
      header: '#ffead5',
      functionBtn: '#f6d8c0',
    },
  },
  coral: {
    key: 'coral',
    label: 'Soft Coral',
    isDark: false,
    colors: {
      background: '#fff5f3',
      surface: '#ffe2dc',
      card: '#fff1ed',
      border: '#efb3a5',
      textPrimary: '#5e3730',
      textSecondary: '#744a41',
      accent: '#e98270',
      accentMuted: '#ffd0c5',
      overlay: 'rgba(116,74,65,0.33)',
      header: '#ffe2dc',
      functionBtn: '#f8d3c8',
    },
  },
};
